
package com.example.soap.client.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerImplService", targetNamespace = "http://service.soap.example.com/", wsdlLocation = "http://localhost:8090/customer?wsdl")
public class CustomerImplService
    extends Service
{

    private final static URL CUSTOMERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERIMPLSERVICE_EXCEPTION;
    private final static QName CUSTOMERIMPLSERVICE_QNAME = new QName("http://service.soap.example.com/", "CustomerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/customer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERIMPLSERVICE_WSDL_LOCATION = url;
        CUSTOMERIMPLSERVICE_EXCEPTION = e;
    }

    public CustomerImplService() {
        super(__getWsdlLocation(), CUSTOMERIMPLSERVICE_QNAME);
    }

    public CustomerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERIMPLSERVICE_QNAME, features);
    }

    public CustomerImplService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERIMPLSERVICE_QNAME);
    }

    public CustomerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERIMPLSERVICE_QNAME, features);
    }

    public CustomerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Customer
     */
    @WebEndpoint(name = "CustomerPort")
    public Customer getCustomerPort() {
        return super.getPort(new QName("http://service.soap.example.com/", "CustomerPort"), Customer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Customer
     */
    @WebEndpoint(name = "CustomerPort")
    public Customer getCustomerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.example.com/", "CustomerPort"), Customer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERIMPLSERVICE_EXCEPTION!= null) {
            throw CUSTOMERIMPLSERVICE_EXCEPTION;
        }
        return CUSTOMERIMPLSERVICE_WSDL_LOCATION;
    }

}
