
package com.example.soap.client.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DuplicateCustomer", targetNamespace = "http://www.soen487.com/lab05")
public class DuplicateCustomer_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DuplicateCustomer faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DuplicateCustomer_Exception(String message, DuplicateCustomer faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DuplicateCustomer_Exception(String message, DuplicateCustomer faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.soap.client.service.DuplicateCustomer
     */
    public DuplicateCustomer getFaultInfo() {
        return faultInfo;
    }

}
