
package com.example.soap.client.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MissCustomer", targetNamespace = "http://www.soen487.com/lab05")
public class MissingCustomer_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MissingCustomer faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MissingCustomer_Exception(String message, MissingCustomer faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MissingCustomer_Exception(String message, MissingCustomer faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.soap.client.service.MissingCustomer
     */
    public MissingCustomer getFaultInfo() {
        return faultInfo;
    }

}
